In [4]:
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('marketing_customer_analysis_clean.csv')  
df

unnamed:_0 customer       state  customer_lifetime_value response  \
0               0  DK49336     Arizona              4809.216960       No   
1               1  KX64629  California              2228.525238       No   
2               2  LZ68649  Washington             14947.917300       No   
3               3  XL78013      Oregon             22332.439460      Yes   
4               4  QA50777      Oregon              9025.067525       No   
...           ...      ...         ...                      ...      ...   
10905       10905  FE99816      Nevada             15563.369440       No   
10906       10906  KX53892      Oregon              5259.444853       No   
10907       10907  TL39050     Arizona             23893.304100       No   
10908       10908  WA60547  California             11971.977650       No   
10909       10909  IV32877  California              6857.519928       No   

       coverage education effective_to_date employmentstatus gender  ...  \
0         Basic   College        2011-02-18         Employed      M  ...   
1         Basic   College        2011-01-18       Unemployed      F  ...   
2         Basic  Bachelor        2011-02-10         Employed      M  ...   
3      Extended   College        2011-01-11         Employed      M  ...   
4       Premium  Bachelor        2011-01-17    Medical Leave      F  ...   
...         ...       ...               ...              ...    ...  ...   
10905   Premium  Bachelor        2011-01-19       Unemployed      F  ...   
10906     Basic   College        2011-01-06         Employed      F  ...   
10907  Extended  Bachelor        2011-02-06         Employed      F  ...   
10908   Premium   College        2011-02-13         Employed      F  ...   
10909     Basic  Bachelor        2011-01-08       Unemployed      M  ...   

       number_of_policies     policy_type        policy  renew_offer_type  \
0                       9  Corporate Auto  Corporate L3            Offer3   
1                       1   Personal Auto   Personal L3            Offer4   
2                       2   Personal Auto   Personal L3            Offer3   
3                       2  Corporate Auto  Corporate L3            Offer2   
4                       7   Personal Auto   Personal L2            Offer1   
...                   ...             ...           ...               ...   
10905                   7   Personal Auto   Personal L1            Offer3   
10906                   6   Personal Auto   Personal L3            Offer2   
10907                   2  Corporate Auto  Corporate L3            Offer1   
10908                   6   Personal Auto   Personal L1            Offer1   
10909                   3   Personal Auto   Personal L1            Offer4   

       sales_channel  total_claim_amount  vehicle_class  vehicle_size  \
0              Agent          292.800000  Four-Door Car       Medsize   
1        Call Center          744.924331  Four-Door Car       Medsize   
2        Call Center          480.000000            SUV       Medsize   
3             Branch          484.013411  Four-Door Car       Medsize   
4             Branch          707.925645  Four-Door Car       Medsize   
...              ...                 ...            ...           ...   
10905            Web         1214.400000     Luxury Car       Medsize   
10906         Branch          273.018929  Four-Door Car       Medsize   
10907            Web          381.306996     Luxury SUV       Medsize   
10908         Branch          618.288849            SUV       Medsize   
10909            Web         1021.719397            SUV       Medsize   

      vehicle_type month  
0                A     2  
1                A     1  
2                A     2  
3                A     1  
4                A     1  
...            ...   ...  
10905            A     1  
10906            A     1  
10907            A     2  
10908            A     2  
10909            A     1  

[10910 rows x 27 columns]

In [5]:
df.select_dtypes(include=np.number)

unnamed:_0  customer_lifetime_value  income  monthly_premium_auto  \
0               0              4809.216960   48029                    61   
1               1              2228.525238       0                    64   
2               2             14947.917300   22139                   100   
3               3             22332.439460   49078                    97   
4               4              9025.067525   23675                   117   
...           ...                      ...     ...                   ...   
10905       10905             15563.369440       0                   253   
10906       10906              5259.444853   61146                    65   
10907       10907             23893.304100   39837                   201   
10908       10908             11971.977650   64195                   158   
10909       10909              6857.519928       0                   101   

       months_since_last_claim  months_since_policy_inception  \
0                     7.000000                             52   
1                     3.000000                             26   
2                    34.000000                             31   
3                    10.000000                              3   
4                    15.149071                             31   
...                        ...                            ...   
10905                15.149071                             40   
10906                 7.000000                             68   
10907                11.000000                             63   
10908                 0.000000                             27   
10909                31.000000                              1   

       number_of_open_complaints  number_of_policies  total_claim_amount  \
0                       0.000000                   9          292.800000   
1                       0.000000                   1          744.924331   
2                       0.000000                   2          480.000000   
3                       0.000000                   2          484.013411   
4                       0.384256                   7          707.925645   
...                          ...                 ...                 ...   
10905                   0.384256                   7         1214.400000   
10906                   0.000000                   6          273.018929   
10907                   0.000000                   2          381.306996   
10908                   4.000000                   6          618.288849   
10909                   0.000000                   3         1021.719397   

       month  
0          2  
1          1  
2          2  
3          1  
4          1  
...      ...  
10905      1  
10906      1  
10907      2  
10908      2  
10909      1  

[10910 rows x 10 columns]

# X-y SPLIT

In [8]:
X = df[['customer_lifetime_value', "income", "monthly_premium_auto", "months_since_last_claim", "months_since_policy_inception", "number_of_open_complaints", "number_of_policies"]]
y = df[['total_claim_amount']]

# Train-test split

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 100)

# SCALING

In [64]:
X_train

customer_lifetime_value  income  monthly_premium_auto  \
8752              5932.560456   48278                    74   
2531              5295.625697       0                    74   
8626              2397.036098   22283                    65   
9496             27420.813180       0                   112   
3985             14727.505260   97785                    73   
...                       ...     ...                   ...   
350               2476.480866   47918                    62   
79                9312.585034   75986                   115   
8039              4874.665223   67467                    61   
6936             21159.301510       0                   108   
5640              4558.498445       0                    65   

      months_since_last_claim  months_since_policy_inception  \
8752                15.149071                              7   
2531                19.000000                             71   
8626                16.000000                             93   
9496                23.000000                             20   
3985                35.000000                             36   
...                       ...                            ...   
350                  2.000000                             51   
79                  11.000000                             44   
8039                 4.000000                             22   
6936                15.000000                             17   
5640                24.000000                             93   

      number_of_open_complaints  number_of_policies  
8752                   0.384256                   4  
2531                   0.000000                   3  
8626                   0.000000                   1  
9496                   0.000000                   2  
3985                   0.000000                   2  
...                         ...                 ...  
350                    0.000000                   1  
79                     0.000000                   3  
8039                   0.000000                   9  
6936                   0.000000                   2  
5640                   0.000000                   9  

[8182 rows x 7 columns]

In [66]:
X_test

customer_lifetime_value  income  monthly_premium_auto  \
1250               2810.464447   26790                    71   
5438               2605.599527   20592                    71   
10156              7451.492020       0                   107   
3441              16477.768430   49825                    70   
682                9192.592887   37388                   117   
...                        ...     ...                   ...   
5063              16727.771860   30915                    72   
10053              5067.208338   29095                   127   
3453               6725.043747       0                    95   
9241               3940.123576   92539                   100   
10449              8295.977271   73556                   104   

       months_since_last_claim  months_since_policy_inception  \
1250                       4.0                             41   
5438                      15.0                             81   
10156                      6.0                             63   
3441                      14.0                             27   
682                       30.0                             21   
...                        ...                            ...   
5063                       1.0                              6   
10053                      2.0                             80   
3453                      15.0                              8   
9241                       1.0                             55   
10449                     31.0                              4   

       number_of_open_complaints  number_of_policies  
1250                         0.0                   1  
5438                         1.0                   1  
10156                        0.0                   8  
3441                         3.0                   2  
682                          0.0                   5  
...                          ...                 ...  
5063                         2.0                   2  
10053                        0.0                   1  
3453                         0.0                   5  
9241                         0.0                   1  
10449                        0.0                   9  

[2728 rows x 7 columns]

In [65]:
from sklearn.preprocessing import MinMaxScaler

In [67]:
scaler = MinMaxScaler()

In [ ]:
#We just have to apply fit once (the X_train)

In [126]:
scaler.fit(X_train)

MinMaxScaler()

In [125]:
scaler.fit(y_train)

MinMaxScaler()

In [ ]:
#Now we transform BOTH: train and test

In [117]:
scaler.fit(y_test)

MinMaxScaler()

In [118]:
scaler.fit(X_test)

MinMaxScaler()

# Creating our model

In [128]:
from sklearn.linear_model import LinearRegression

In [129]:
lm = LinearRegression()

In [131]:
model = lm.fit(scaler.transform(X_train), y_train)

In [132]:
model.coef_

array([[ -42.27972663, -335.35569563, 1247.73415775,   -4.79849607,
         -17.61939479,  -13.73769717,    1.39763658]])

In [133]:
model.intercept_

array([405.49865577])

In [76]:
#Now we have the equation for standarized values.

In [ ]:
#Reshape: you want seven columns!!!!

#I choose the first row: [0.01279242, 0.26795091, 0.04219409, ..., 0.41414141, 0., 0.]

In [111]:
random_value = np.array([0.01279242, 0.26795091, 0.04219409, 0.11428571, 0.41414141,
       0.        , 0.         ]).reshape(1,-1)

In [112]:
random_value.shape

(1, 7)

In [113]:
model.predict(random_value)

array([[359.90061875]])

# Create "real vs predicted" DataFrame¶

In [134]:
y_pred = np.array(model.predict(scaler.transform(X_test)))

In [135]:
pd.DataFrame(y_pred)[0]

0       359.900622
1       369.436766
2       633.571062
3       262.323465
4       563.439802
           ...    
2723    344.399776
2724    638.988004
2725    578.855792
2726    289.292097
2727    377.802931
Name: 0, Length: 2728, dtype: float64

In [136]:
y_pred.shape

(2728, 1)

In [140]:
real_vs_pred = pd.DataFrame({'y_test': y_test['total_claim_amount'], 'y_pred':pd.DataFrame(y_pred)[0]})

In [141]:
real_vs_pred

y_test      y_pred
0     340.800000  359.900622
1     195.153339  369.436766
2     770.400000  633.571062
3     336.000000  262.323465
4     561.600000  563.439802
...          ...         ...
2723  345.600000  344.399776
2724  664.280864  638.988004
2725  684.000000  578.855792
2726   25.713622  289.292097
2727  497.684017  377.802931

[2728 rows x 2 columns]