In [1]:
import seaborn as sns
import pandas as pd

In [2]:
p_df = sns.load_dataset('penguins')

In [3]:
p_df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [4]:
p_df = p_df.dropna()

## X-y split

In [5]:
X = p_df[['flipper_length_mm']]
y = p_df[['body_mass_g']]

## Train-test split

In [8]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 100)

## Creating our model

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
lm = LinearRegression()

In [23]:
model = lm.fit(X_train, y_train)

In [24]:
model.coef_

array([[48.46455556]])

In [25]:
model.intercept_

array([-5538.16645549])

In [30]:
import numpy as np

## Predict the weight of a random penguin

In [34]:
random_peng = np.array([215]).reshape(-1,1)

In [35]:
model.predict(random_peng)

C:\Users\Aleks\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[4881.71298884]])

## Create "real vs predicted" DataFrame

In [49]:
y_pred = np.array(model.predict(X_test))

In [58]:
y_test.reset_index(inplace=True)

In [54]:
pd.DataFrame(y_pred)[0]

0     3524.705433
1     4397.067433
2     4881.712989
3     3670.099100
4     4590.925656
         ...     
79    4639.390211
80    3573.169989
81    3330.847211
82    3427.776322
83    3960.886433
Name: 0, Length: 84, dtype: float64

In [47]:
y_pred.shape

(84, 1)

In [59]:
real_vs_pred = pd.DataFrame({'y_test': y_test['body_mass_g'], 'y_pred':pd.DataFrame(y_pred)[0]})

In [60]:
real_vs_pred

y_test       y_pred
0   3350.0  3524.705433
1   4550.0  4397.067433
2   4850.0  4881.712989
3   3450.0  3670.099100
4   4600.0  4590.925656
..     ...          ...
79  4550.0  4639.390211
80  3050.0  3573.169989
81  3075.0  3330.847211
82  3700.0  3427.776322
83  3550.0  3960.886433

[84 rows x 2 columns]

## Compute the MSE

In [64]:
from sklearn.metrics import mean_squared_error as mse

In [65]:
mse(real_vs_pred['y_test'], real_vs_pred['y_pred'])

165251.77220034634